name: Jules Invoke
description: 'Invoke Jules, an AI-powered coding agent, to perform tasks on your codebase.'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  prompt:
    description: 'The prompt to pass to Jules'
    required: true
    type: string
  include_last_commit:
    description: 'Whether to pass content of the last commit'
    type: boolean
    default: false
  include_commit_log:
    description: 'Whether to pass commit history'
    type: boolean
    default: false
  starting_branch:
    description: 'The branch for Jules to start from'
    required: false
    type: string
    default: 'main'
  jules_api_key:
    description: 'The Jules API key to use for authentication'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 30

    - name: Create initial prompt
      env:
        USER_PROMPT: ${{ inputs.prompt }}
      shell: bash
      run: |
        printf "%s" "$USER_PROMPT" > prompt.txt

    - name: Save last commit content
      if: ${{ inputs.include_last_commit }}
      shell: bash
      run: |
        printf '\n\nContent of the latest commit (in the format of `git show`):\n' >> prompt.txt
        printf '```\n' >> prompt.txt
        git show       >> prompt.txt
        printf '```\n' >> prompt.txt

    - name: Save git log
      if: ${{ inputs.include_commit_log }}
      shell: bash
      run: |
        printf '\n\nLog of the last 20 commits (in the format of `git log --stat`):\n' >> prompt.txt
        printf '```\n'     >> prompt.txt
        git log -20 --stat >> prompt.txt
        printf '```\n'     >> prompt.txt

    - name: Assemble Jules payload
      env:
        STARTING_BRANCH: ${{ inputs.starting_branch }}
        REPO_FULL_NAME: ${{ github.repository }}
      shell: bash
      run: |
        jq -n --rawfile jules_prompt prompt.txt --arg starting_branch "$STARTING_BRANCH" --arg repo_full_name "$REPO_FULL_NAME" '{
            "prompt": $jules_prompt,
            "sourceContext": {
              "source": "sources/github/\($repo_full_name)",
              "githubRepoContext": {
                "startingBranch": $starting_branch
              }
            },
            "requirePlanApproval": false,
            "automationMode": "AUTO_CREATE_PR"
          }' > jules_payload.json

    - name: Invoke Jules
      env:
        JULES_API_KEY: ${{ inputs.jules_api_key }}
      shell: bash
      run: |
        curl -fsSL 'https://jules.googleapis.com/v1alpha/sessions' \
          -X POST \
          -H "Content-Type: application/json" \
          -H "X-Goog-Api-Key: $JULES_API_KEY" \
          -d @jules_payload.json
